// Required-fields documentation for the PostCompact example payload.
// Grounded in src/types/contexts.ts (PostCompactContext) and
// docs/domain/raw-claude-ai/hook-docs/PostCompact.md.

export default {
  required: [
    { name: 'event', type: 'string', description: 'Must be "PostCompact".' },
    {
      name: 'trigger',
      type: 'string',
      description:
        'Whether compaction was triggered manually ("manual") or automatically ("auto").',
    },
    {
      name: 'compactSummary',
      type: 'string',
      description: 'The conversation summary generated by the compact operation.',
    },
  ],
} as const
