#!/usr/bin/env bun
// Build script: generates bundled .d.ts from the type surface.
// Usage: bun run scripts/generate-types.ts

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { VERSION } from '../src/version.js'

const ROOT = resolve(dirname(import.meta.dir))
const OUT_DIR = resolve(ROOT, 'src/generated')
const OUT_FILE = resolve(OUT_DIR, 'clooks-types.d.ts.txt')
// Mirror copy as a real `.d.ts` file. The runtime path uses the `.txt` form
// (bun text-import); `scripts/verify-types-emit.ts` needs to `import type`
// from the bundle under `tsc --noEmit`. Both files must stay in sync.
const OUT_FILE_DTS = resolve(OUT_DIR, 'clooks-types.d.ts')
// Local repo copy. This repo's `.clooks/hooks/*.ts` compile against this file
// (same source-of-truth as the binary-embedded `.txt`). Kept byte-identical
// so authors editing in-repo see the same surface as downstream projects.
const OUT_FILE_LOCAL_HOOKS = resolve(ROOT, '.clooks/hooks/types.d.ts')
const ENTRY = resolve(ROOT, 'src/types/index.ts')
const TSCONFIG = resolve(ROOT, 'tsconfig.json')

mkdirSync(OUT_DIR, { recursive: true })

const proc = Bun.spawnSync([
  'npx',
  'dts-bundle-generator',
  '--project',
  TSCONFIG,
  '--no-check',
  '--export-referenced-types=false',
  ENTRY,
  '--out-file',
  OUT_FILE,
])

if (proc.exitCode !== 0) {
  const stderr = proc.stderr.toString()
  console.error('dts-bundle-generator failed:', stderr)
  process.exit(1)
}

// Read generated file, strip tool banner, prepend our header
const raw = readFileSync(OUT_FILE, 'utf-8')

const lines = raw.split('\n')
const stripped = lines
  .filter((line) => !line.startsWith('// Generated by dts-bundle-generator'))
  .join('\n')
  .replace(/^\n+/, '') // remove leading blank lines left after stripping

const header = [
  `// Clooks v${VERSION} — generated type declarations`,
  '// Do not edit. Regenerate with: clooks types',
  '',
].join('\n')

const finalContent = header + stripped
writeFileSync(OUT_FILE, finalContent)
// Mirror to a real `.d.ts` file for tooling that imports types directly
// (e.g. `scripts/verify-types-emit.ts`). Kept byte-identical to the `.txt`.
writeFileSync(OUT_FILE_DTS, finalContent)
// Mirror to .clooks/hooks/types.d.ts so this repo's local hooks compile
// against the regenerated surface.
mkdirSync(dirname(OUT_FILE_LOCAL_HOOKS), { recursive: true })
writeFileSync(OUT_FILE_LOCAL_HOOKS, finalContent)

console.log(`Generated ${OUT_FILE} (${finalContent.length} bytes)`)
console.log(`Generated ${OUT_FILE_DTS} (${finalContent.length} bytes)`)
console.log(`Generated ${OUT_FILE_LOCAL_HOOKS} (${finalContent.length} bytes)`)
