#!/usr/bin/env bun
// Build script: generates bundled .d.ts from the type surface.
// Usage: bun run scripts/generate-types.ts

import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, resolve } from "node:path"
import { VERSION } from "../src/index.js"

const ROOT = resolve(dirname(import.meta.dir))
const OUT_DIR = resolve(ROOT, "src/generated")
const OUT_FILE = resolve(OUT_DIR, "clooks-types.d.ts.txt")
const ENTRY = resolve(ROOT, "src/types/index.ts")
const TSCONFIG = resolve(ROOT, "tsconfig.json")

mkdirSync(OUT_DIR, { recursive: true })

const proc = Bun.spawnSync([
  "npx",
  "dts-bundle-generator",
  "--project", TSCONFIG,
  "--no-check",
  "--export-referenced-types=false",
  ENTRY,
  "--out-file", OUT_FILE,
])

if (proc.exitCode !== 0) {
  const stderr = proc.stderr.toString()
  console.error("dts-bundle-generator failed:", stderr)
  process.exit(1)
}

// Read generated file, strip tool banner, prepend our header
const raw = readFileSync(OUT_FILE, "utf-8")

const lines = raw.split("\n")
const stripped = lines
  .filter((line) => !line.startsWith("// Generated by dts-bundle-generator"))
  .join("\n")
  .replace(/^\n+/, "") // remove leading blank lines left after stripping

const header = [
  `// Clooks v${VERSION} — generated type declarations`,
  "// Do not edit. Regenerate with: clooks types",
  "",
].join("\n")

writeFileSync(OUT_FILE, header + stripped)

console.log(`Generated ${OUT_FILE} (${(header + stripped).length} bytes)`)
