#!/usr/bin/env bun
// Regenerates page/version.js from src/version.ts.
// Wired into lefthook pre-commit so the landing page version indicators
// stay in lockstep with the CLI's VERSION constant.

import { readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '..')

const src = readFileSync(resolve(repo, 'src/version.ts'), 'utf8')
const match = src.match(/export const VERSION = '([^']+)'/)
if (!match) {
  console.error('sync-page-version: failed to extract VERSION from src/version.ts')
  process.exit(1)
}
const version = match[1]

const out = `// Generated by scripts/sync-page-version.ts — do not edit by hand.
// Source of truth: src/version.ts
window.CLOOKS_VERSION = ${JSON.stringify(version)};
`

writeFileSync(resolve(repo, 'page/version.js'), out)
console.log(`page/version.js synced to ${version}`)
