#!/usr/bin/env bun

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SemVer } from 'semver'
import { MIN_RUNTIME_VERSION } from '../src/installation-metadata'
import { VERSION } from '../src/version'

export interface SyncReleaseVersionOptions {
  repo: string
  version: string
  marketplace?: string
  check?: boolean
}

export interface SyncReleaseVersionResult {
  changed: string[]
}

interface PlannedFile {
  path: string
  next: string
  changed: boolean
}

export class ReleaseVersionDriftError extends Error {
  readonly paths: string[]

  constructor(paths: string[]) {
    super(`release version drift in: ${paths.join(', ')}`)
    this.name = 'ReleaseVersionDriftError'
    this.paths = paths
  }
}

export function formatPageVersion(version: string): string {
  return `// Generated by scripts/sync-page-version.ts — do not edit by hand.
// Source of truth: src/version.ts
window.CLOOKS_VERSION = ${JSON.stringify(version)};
`
}

function read(path: string): string {
  try {
    return readFileSync(path, 'utf8')
  } catch (error) {
    throw new Error(`cannot read ${path}: ${errorMessage(error)}`)
  }
}

function readGenerated(path: string): string | undefined {
  try {
    return readFileSync(path, 'utf8')
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return undefined
    throw new Error(`cannot read ${path}: ${errorMessage(error)}`)
  }
}

function parseObject(path: string, source: string): Record<string, unknown> {
  let value: unknown
  try {
    value = JSON.parse(source)
  } catch (error) {
    throw new Error(`invalid JSON in ${path}: ${errorMessage(error)}`)
  }
  if (value === null || typeof value !== 'object' || Array.isArray(value)) {
    throw new Error(`expected a JSON object in ${path}`)
  }
  return value as Record<string, unknown>
}

function requireVersion(path: string, object: Record<string, unknown>): string {
  if (typeof object.version !== 'string') {
    throw new Error(`expected string property "version" in ${path}`)
  }
  return object.version
}

function jsonPlan(
  path: string,
  version: string,
  update: (object: Record<string, unknown>) => string,
): PlannedFile {
  const current = read(path)
  const object = parseObject(path, current)
  const previous = update(object)
  return {
    path,
    next: JSON.stringify(object, null, 2) + '\n',
    changed: previous !== version,
  }
}

function pagePlan(path: string, version: string): PlannedFile {
  const next = formatPageVersion(version)
  return { path, next, changed: readGenerated(path) !== next }
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error)
}

function fullSemVer(label: string, value: string): SemVer {
  try {
    const parsed = new SemVer(value)
    const prerelease = parsed.prerelease.length > 0 ? `-${parsed.prerelease.join('.')}` : ''
    const build = parsed.build.length > 0 ? `+${parsed.build.join('.')}` : ''
    if (value === `${parsed.major}.${parsed.minor}.${parsed.patch}${prerelease}${build}`) {
      return parsed
    }
  } catch {
    // Use the same error for malformed and non-canonical versions.
  }
  throw new Error(`${label} must be full SemVer, received ${JSON.stringify(value)}`)
}

function displayPath(path: string, repo: string, marketplace?: string): string {
  for (const root of [repo, marketplace]) {
    if (!root) continue
    const candidate = relative(root, path)
    if (candidate && !candidate.startsWith('..')) return candidate
  }
  return path
}

export function syncReleaseVersion(options: SyncReleaseVersionOptions): SyncReleaseVersionResult {
  const repo = resolve(options.repo)
  const marketplace = options.marketplace ? resolve(options.marketplace) : undefined
  const version = options.version
  const release = fullSemVer('release version', version)
  const minimumRuntime = fullSemVer('minimum runtime version', MIN_RUNTIME_VERSION)
  if (minimumRuntime.compare(release) > 0) {
    throw new Error(
      `minimum runtime version ${MIN_RUNTIME_VERSION} exceeds release version ${version}`,
    )
  }

  // Build the complete plan before writing so malformed or missing inputs cannot cause partial edits.
  const plans: PlannedFile[] = [
    jsonPlan(resolve(repo, 'package.json'), version, (object) => {
      const previous = requireVersion(resolve(repo, 'package.json'), object)
      object.version = version
      return previous
    }),
    pagePlan(resolve(repo, 'page/version.js'), version),
  ]

  if (marketplace) {
    for (const manifest of [
      'clooks/.claude-plugin/plugin.json',
      'clooks/.codex-plugin/plugin.json',
    ]) {
      const path = resolve(marketplace, manifest)
      plans.push(
        jsonPlan(path, version, (object) => {
          const previous = requireVersion(path, object)
          object.version = version
          return previous
        }),
      )
    }

    const listingPath = resolve(marketplace, '.claude-plugin/marketplace.json')
    plans.push(
      jsonPlan(listingPath, version, (object) => {
        if (!Array.isArray(object.plugins)) {
          throw new Error(`expected array property "plugins" in ${listingPath}`)
        }
        const matches = object.plugins.filter(
          (entry): entry is Record<string, unknown> =>
            entry !== null &&
            typeof entry === 'object' &&
            !Array.isArray(entry) &&
            entry.name === 'clooks',
        )
        if (matches.length !== 1) {
          throw new Error(`expected exactly one plugin named "clooks" in ${listingPath}`)
        }
        const previous = requireVersion(`${listingPath} clooks listing`, matches[0]!)
        matches[0]!.version = version
        return previous
      }),
    )
  }

  const changedPlans = plans.filter((plan) => plan.changed)
  const changed = changedPlans.map((plan) => displayPath(plan.path, repo, marketplace))
  if (options.check && changed.length > 0) throw new ReleaseVersionDriftError(changed)

  for (const plan of changedPlans) {
    writeFileSync(plan.path, plan.next)
  }
  return { changed }
}

interface CliOptions {
  check: boolean
  marketplace?: string
}

function parseArgs(args: string[]): CliOptions {
  let check = false
  let marketplace: string | undefined
  for (let index = 0; index < args.length; index++) {
    const argument = args[index]
    if (argument === '--check') {
      if (check) throw new Error('--check may only be specified once')
      check = true
    } else if (argument === '--marketplace') {
      if (marketplace !== undefined) throw new Error('--marketplace may only be specified once')
      const value = args[++index]
      if (!value || value.startsWith('--')) throw new Error('--marketplace requires a path')
      marketplace = resolve(value)
    } else {
      throw new Error(`unknown argument: ${argument}`)
    }
  }
  return { check, marketplace }
}

async function main(): Promise<void> {
  try {
    const options = parseArgs(process.argv.slice(2))
    const repo = resolve(dirname(fileURLToPath(import.meta.url)), '..')
    const result = syncReleaseVersion({ repo, version: VERSION, ...options })
    const scope = options.marketplace ? 'local and marketplace' : 'local'
    if (options.check) {
      console.log(`Release versions are in sync at ${VERSION} (${scope}).`)
    } else if (result.changed.length === 0) {
      console.log(`Release versions already synced at ${VERSION} (${scope}).`)
    } else {
      console.log(`Synced ${result.changed.join(', ')} to ${VERSION}.`)
    }
  } catch (error) {
    console.error(`sync-release-version: ${errorMessage(error)}`)
    process.exitCode = 1
  }
}

if (import.meta.main) await main()
