#!/usr/bin/env bun
// Build-time gate. Verifies the `src/examples/contexts/` corpus stays in
// lock-step with
// `src/types/contexts.ts`:
//
//   1. Every `<Event>.json` has a sibling `<Event>.meta.ts` and vice versa
//      (1:1 pairing across the 22 supported events).
//   2. Each `<Event>.json`'s payload is assignable to the cleaned-up Context
//      type for that event — i.e. it satisfies `CreateContextPayload<<Event>>`,
//      the same payload shape `createContext` / `createHarnessContext` accept.
//      The check inlines each JSON payload as a TypeScript object literal and
//      asserts via `as const satisfies <Type>`. Inlining (not `JSON.parse`) is
//      required: a `JSON.parse(...)` result is `any` and silently passes every
//      type error.
//   3. `TOOL_INPUT_DOCS`'s keys are exactly `keyof ToolInputMap`. If a tool is
//      added to `ToolInputMap` without docs (or vice versa), `tsc` errors.
//
// The gate writes a synthetic file to `tmp/verify-context-examples/gen.ts`
// (gitignored per `.gitignore`'s `tmp/*` rule) and runs `bunx tsc --noEmit`
// over it using the project's `tsconfig.json`.
//
// Usage: `bun run scripts/verify-context-examples.ts`
// Wired into `lefthook.yml`'s `pre-commit` block alongside `bundle-up-to-date`.

import { mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'

const ROOT = resolve(dirname(import.meta.dir))
const CONTEXTS_DIR = resolve(ROOT, 'src/examples/contexts')
const TMP_DIR = resolve(ROOT, 'tmp/verify-context-examples')
const GEN_FILE = resolve(TMP_DIR, 'gen.ts')

// --- 1:1 pairing check ---------------------------------------------------

const entries = readdirSync(CONTEXTS_DIR)
const jsonNames = new Set<string>()
const metaNames = new Set<string>()
for (const entry of entries) {
  if (entry.endsWith('.meta.ts')) {
    metaNames.add(entry.slice(0, -'.meta.ts'.length))
  } else if (entry.endsWith('.json')) {
    jsonNames.add(entry.slice(0, -'.json'.length))
  }
}

const missingMeta: string[] = []
for (const name of jsonNames) {
  if (!metaNames.has(name)) missingMeta.push(name)
}
const missingJson: string[] = []
for (const name of metaNames) {
  if (!jsonNames.has(name)) missingJson.push(name)
}

if (missingMeta.length > 0 || missingJson.length > 0) {
  console.error('verify-context-examples: 1:1 pairing failure in src/examples/contexts/')
  if (missingMeta.length > 0) {
    console.error(`  Missing .meta.ts for: ${missingMeta.sort().join(', ')}`)
  }
  if (missingJson.length > 0) {
    console.error(`  Missing .json for: ${missingJson.sort().join(', ')}`)
  }
  process.exit(1)
}

const events = [...jsonNames].sort()

// --- Generate the synthetic ----------------------------------------------

mkdirSync(TMP_DIR, { recursive: true })

const lines: string[] = []
lines.push('// AUTO-GENERATED by scripts/verify-context-examples.ts. Do not edit.')
lines.push('// This file is recreated on every run; `tmp/` is gitignored.')
lines.push('')
lines.push("import type { CreateContextPayload } from '../../src/testing/create-context.js'")
lines.push("import { TOOL_INPUT_DOCS } from '../../src/examples/tool-inputs.meta.js'")
lines.push("import type { ToolInputMap } from '../../src/types/contexts.js'")
lines.push('')

for (const event of events) {
  const jsonPath = resolve(CONTEXTS_DIR, `${event}.json`)
  const raw = readFileSync(jsonPath, 'utf-8').trimEnd()
  // Sanity: must parse as JSON. We inline the source verbatim so TS sees an
  // object literal with full literal-type narrowing — `JSON.parse` would
  // erase the type information and let drift slip through.
  try {
    JSON.parse(raw)
  } catch (err) {
    console.error(`verify-context-examples: ${event}.json is not valid JSON: ${String(err)}`)
    process.exit(1)
  }
  const constName = `_${event}_payload`
  lines.push(`const ${constName} = ${raw} as const satisfies CreateContextPayload<'${event}'>`)
  lines.push(`void ${constName}`)
  lines.push('')
}

// TOOL_INPUT_DOCS keys must exactly match `keyof ToolInputMap`. Both
// extends-checks together produce a compile error if either side is wider.
lines.push('// TOOL_INPUT_DOCS key-coverage check (M3): exact match with `keyof ToolInputMap`.')
lines.push('type _ToolInputDocsKeyCheck =')
lines.push('  keyof typeof TOOL_INPUT_DOCS extends keyof ToolInputMap')
lines.push('    ? keyof ToolInputMap extends keyof typeof TOOL_INPUT_DOCS')
lines.push('      ? true')
lines.push('      : never')
lines.push('    : never')
lines.push('const _toolInputDocsKeyCheck: _ToolInputDocsKeyCheck = true')
lines.push('void _toolInputDocsKeyCheck')
lines.push('')

writeFileSync(GEN_FILE, lines.join('\n'))

// Derived tsconfig that extends the project's settings and includes only the
// synthetic. `--project <file>` and a positional path are mutually exclusive
// in `tsc`, so we can't combine them; the cheapest way to inherit `strict`,
// `noUncheckedIndexedAccess`, etc., is a tiny extending config.
const TSCONFIG_FILE = resolve(TMP_DIR, 'tsconfig.json')
writeFileSync(
  TSCONFIG_FILE,
  JSON.stringify(
    {
      extends: '../../tsconfig.json',
      compilerOptions: { noEmit: true },
      include: ['gen.ts'],
      exclude: [],
    },
    null,
    2,
  ),
)

// --- Type-check the synthetic --------------------------------------------

const proc = Bun.spawnSync(['npx', 'tsc', '--noEmit', '--project', TSCONFIG_FILE], {
  cwd: ROOT,
  stderr: 'pipe',
  stdout: 'pipe',
})

if (proc.exitCode !== 0) {
  const stdout = proc.stdout.toString()
  const stderr = proc.stderr.toString()
  console.error('verify-context-examples: tsc reported errors against the generated synthetic.')
  if (stdout.length > 0) console.error(stdout)
  if (stderr.length > 0) console.error(stderr)
  console.error(`Synthetic kept for inspection: ${GEN_FILE}`)
  process.exit(1)
}

console.log(
  `verify-context-examples: ${events.length} payload pairs validated. TOOL_INPUT_DOCS keys match ToolInputMap. ✓`,
)
